/**
  创建存储过程，用于生成订单号 utf8编码格式
 */
DELIMITER $$

USE `SUPER_SHOP` $$

DROP PROCEDURE IF EXISTS `SEQ_NO` $$

CREATE DEFINER = `ROOT` @`LOCALHOST` PROCEDURE `SEQ_NO` ()
  BEGIN
    DECLARE V_CNT INT ;
    DECLARE V_TIMESTR INT ;
    DECLARE ROWCOUNT BIGINT ;
    SET V_TIMESTR = DATE_FORMAT(NOW(), '%Y%M%D') ;
    SELECT
      ROUND(RAND() * 10, 0) + 1 INTO V_CNT ;
    START TRANSACTION ;
    UPDATE
      ORDER_SEQ
    SET
      ORDER_SN = ORDER_SN + V_CNT
    WHERE TIMESTR = V_TIMESTR ;
    IF ROW_COUNT() = 0
    THEN
      INSERT INTO ORDER_SEQ (TIMESTR, ORDER_SN)
      VALUES
        (V_TIMESTR, V_CNT) ;
    END IF ;
    SELECT
      CONCAT(V_TIMESTR, LPAD(ORDER_SN, 7, 0)) AS ORDER_SN
    FROM
      ORDER_SEQ
    WHERE TIMESTR = V_TIMESTR ;
    COMMIT ;
  END $$

DELIMITER ;